language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

sudo: false
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-4.9
     - g++-4.9

install: CXX="g++-4.9" CC="gcc-4.9" ./install-stockfish

script: python test.py -v
